name: "[CI] Continuous Integration"

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      ## [Commons_CI_Steps]
      - uses: actions/checkout@v3
      #####################
      - name: "Debug"
        run: "ls -la"
      - name: "Install Dependencies"
        run: "npm ci"
      - name: "Lint"
        run: "npm run lint"
  test-e2e:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1
      options: --user 1001
    steps:
      ## [Commons_CI_Steps]
      - uses: actions/checkout@v3
      #####################
      - name: "Install Dependencies"
        run: "npm ci"
      - name: "Run Cypress"
        run: "npm run test"
